apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-hello-deployment
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-hello
  template:
    metadata:
      labels:
        app: angular-hello
    spec:
      containers:
      - name: angular-hello
        image: angular-hello/app:v1.0.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"

---

apiVersion: v1
kind: Service
metadata:
  name: angular-hello
  namespace: devops
spec:
  selector:
    app: angular-hello
  ports:
  - port: 4000
    targetPort: 4000
    name: tcp

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: angular-hello-ingress
  namespace: devops
  annotations:
    kubernetes.io/ingressClassName: "traefik"
spec:
  rules:
  - host: "www.192.168.56.2.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: angular-hello
            port: 
              number: 4000